name: Update ANRO Branch

on:
  push:
    branches:
      - fszyszko2

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout fszyszko2 branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set user email and name
      run: |
        git config user.email "01168917@pw.edu.pl"
        git config user.name "yRagax"

    - name: Fetch all branches
      run: git fetch origin ANRO-system || echo "No ANRO-system branch yet"

    - name: Create ANRO-system from fszyszko2
      run: |
        git checkout -B ANRO-system origin/fszyszko2

    - name: Remove lines
      run: |
        sed -i '/from tf2_ros import TransformBroadcaster/d' dobot_state_updater/dobot_state_updater/dobot_state_publ.py
        sed -i '/self\.publisher_joints_rviz = self\.create_publisher(JointState, '\''joint_states'\'', 10)/d' dobot_state_updater/dobot_state_updater/dobot_state_publ.py
        sed -i '/self\.br = TransformBroadcaster(self)/d' dobot_state_updater/dobot_state_updater/dobot_state_publ.py
        sed -i '/self\.publisher_joints_rviz\.publish(joint_state)/d' dobot_state_updater/dobot_state_updater/dobot_state_publ.py
        sed -i '/self\.br\.sendTransform(t)/d' dobot_state_updater/dobot_state_updater/dobot_state_publ.py
    
    - name: Remove files
      run: |
        rm -rf dobot_demos
        rm -rf dobot_description
        rm -rf dobot_visualization_tools

    - name: Commit and push changes
      run: |
        if ! git diff --quiet; then
          git commit -am "Remove files and lines specific for ANRO lab classes"
          git push origin ANRO-system --force
        else
          echo "No changes to commit"
        fi
